services:
  - type: web
    name: event-organizer-server
    env: node
    plan: free
    root: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  - type: static
    name: event-organizer-client
    buildCommand: cd client/client && npm install && npm run build
    staticPublishPath: client/client/build
